# Copyright 2025 Erik Lönroth
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = format, lint, static, unit
min_version = 4.0.0

[testenv]
allowlist_externals = uv
set_env =
    PYTHONPATH = {tox_root}/lib:{tox_root}/src
pass_env =
    CHARM_PATH

[testenv:format]
commands =
    uv run ruff format src tests
    uv run ruff check --fix src tests

[testenv:lint]
commands =
    uv run codespell {tox_root}
    uv run ruff check src tests
    uv run ruff format --check src tests

[testenv:unit]
commands =
    uv run coverage run --source=src -m pytest -v tests/unit
    uv run coverage report

[testenv:static]
commands =
    uv run pyright src

[testenv:integration]
commands =
    uv run pytest tests/integration -v
