# Copyright 2025 Erik Lönroth
# See LICENSE file for licensing details.

"""Workload management helpers for Grafana Alloy."""

from __future__ import annotations

import logging
import os
import pwd
import re
import shlex
import shutil
import subprocess
import time
from pathlib import Path
from typing import Iterable

try:
    from .config_builder import (
        DEFAULT_CONFIG_BACKUP_PATH,
        DEFAULT_CONFIG_PATH,
        DEFAULT_PACKAGE_CONFIG_BACKUP_PATH,
        DEFAULT_SYSTEMD_DEFAULTS_PATH,
    )
except ImportError:
    from config_builder import (
        DEFAULT_CONFIG_BACKUP_PATH,
        DEFAULT_CONFIG_PATH,
        DEFAULT_PACKAGE_CONFIG_BACKUP_PATH,
        DEFAULT_SYSTEMD_DEFAULTS_PATH,
    )

logger = logging.getLogger(__name__)

GENERATED_CONFIG_HEADER = (
    "// This file is generated by Juju. Manual changes will be overwritten.\n"
    "// Adjust charm config to update this file.\n"
)
_GENERATED_HEADER_PREFIX = "// This file is generated by Juju."

GRAFANA_APT_SOURCE = "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
GRAFANA_GPG_KEY_URL = "https://apt.grafana.com/gpg.key"

DEFAULT_START_TIMEOUT = 60
DEFAULT_VERIFY_TIMEOUT = 30
DEFAULT_STATUS_TIMEOUT = 10


def _run(cmd: Iterable[str], *, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
    """Run a command and return the completed process."""
    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive"}
    return subprocess.run(
        list(cmd),
        check=True,
        text=True,
        capture_output=True,
        timeout=timeout,
        env=env,
    )


def _run_shell(cmd: str, *, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
    """Run a shell command."""
    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive"}
    return subprocess.run(
        cmd,
        check=True,
        text=True,
        capture_output=True,
        timeout=timeout,
        env=env,
        shell=True,
    )


def _systemctl(*args: str) -> None:
    """Run a systemctl command."""
    _run(["systemctl", *args])


def _wait_for_active(service: str, *, timeout: int = DEFAULT_START_TIMEOUT) -> None:
    """Wait for a systemd service to become active."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            _run(["systemctl", "is-active", "--quiet", service])
            return
        except subprocess.CalledProcessError:
            time.sleep(1)
    raise RuntimeError(f"Service {service} did not become active within {timeout} seconds")


def install() -> None:
    """Install Alloy from the Grafana APT repository."""
    _run(["apt-get", "update"])
    _run(["apt-get", "install", "-y", "wget", "gpg"])
    _run(["mkdir", "-p", "/etc/apt/keyrings"])
    _run_shell(f"wget -q -O - {GRAFANA_GPG_KEY_URL} | gpg --dearmor > /etc/apt/keyrings/grafana.gpg")
    _run_shell(f'echo "{GRAFANA_APT_SOURCE}" | tee /etc/apt/sources.list.d/grafana.list')
    _run(["apt-get", "update"])
    _run(["apt-get", "install", "-y", "alloy"])


def start() -> None:
    """Start Alloy."""
    _systemctl("enable", "--now", "alloy")
    _wait_for_active("alloy")


def stop() -> None:
    """Stop Alloy."""
    _systemctl("stop", "alloy")


def restart() -> None:
    """Restart Alloy."""
    try:
        _systemctl("restart", "alloy")
    except subprocess.CalledProcessError:
        _systemctl("reset-failed", "alloy")
        _systemctl("start", "alloy")
    _wait_for_active("alloy")


def reload() -> None:
    """Reload Alloy."""
    _systemctl("reload", "alloy")


def custom_args_applied(custom_args: str) -> bool:
    """Return whether the running Alloy process includes the expected custom args."""
    try:
        result = _run(["systemctl", "show", "--property=MainPID", "--value", "alloy"])
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False
    pid = result.stdout.strip()
    if not pid or pid == "0":
        return False
    try:
        argv = [arg.decode("utf-8") for arg in Path(f"/proc/{pid}/cmdline").read_bytes().split(b"\0") if arg]
    except OSError:
        return False
    required_tokens = shlex.split(custom_args)
    return all(token in argv for token in required_tokens)


def get_version() -> str | None:
    """Return the installed Alloy version."""
    try:
        result = _run(["alloy", "--version"])
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    output = f"{result.stdout}\n{result.stderr}".strip()
    match = re.search(
        r"\bversion\s+v?([0-9]+(?:\.[0-9]+){1,3}(?:[-+][0-9A-Za-z.-]+)?)\b",
        output,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(1)
    fallback = re.search(r"\bv?([0-9]+(?:\.[0-9]+){1,3}(?:[-+][0-9A-Za-z.-]+)?)\b", output)
    return fallback.group(1) if fallback else None


def verify_config(*, config_path: Path, timeout: int = DEFAULT_VERIFY_TIMEOUT) -> None:
    """Validate Alloy configuration using ``alloy fmt``."""
    _run(["alloy", "fmt", str(config_path)], timeout=timeout)


def is_active(*, timeout: int = DEFAULT_STATUS_TIMEOUT) -> bool:
    """Return whether the Alloy service is active."""
    try:
        _run(["systemctl", "is-active", "--quiet", "alloy"], timeout=timeout)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def read_custom_args(*, defaults_path: Path = Path(DEFAULT_SYSTEMD_DEFAULTS_PATH)) -> str | None:
    """Read ``CUSTOM_ARGS`` from the Alloy defaults file."""
    try:
        content = defaults_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError as exc:
        logger.warning("Failed to read %s: %s", defaults_path, exc)
        return None
    for line in content.splitlines():
        if line.strip().startswith("CUSTOM_ARGS="):
            value = line.split("=", 1)[1].strip()
            return _strip_quotes(value)
    return None


def write_custom_args(
    custom_args: str | None,
    *,
    defaults_path: Path = Path(DEFAULT_SYSTEMD_DEFAULTS_PATH),
) -> None:
    """Write ``CUSTOM_ARGS`` to the Alloy defaults file."""
    lines: list[str] = []
    existing = False
    if defaults_path.exists():
        try:
            lines = defaults_path.read_text(encoding="utf-8").splitlines()
        except OSError as exc:
            logger.warning("Failed to read %s: %s", defaults_path, exc)
            lines = []
    updated: list[str] = []
    for line in lines:
        if line.strip().startswith("CUSTOM_ARGS="):
            existing = True
            if custom_args is not None:
                updated.append(_format_custom_args(custom_args))
            continue
        updated.append(line)
    if not existing and custom_args is not None:
        updated.append(_format_custom_args(custom_args))
    if not updated and custom_args is None and not defaults_path.exists():
        return
    defaults_path.parent.mkdir(parents=True, exist_ok=True)
    _write_file_atomic(defaults_path, "\n".join(updated).rstrip() + "\n")


def write_config_text(
    config_text: str,
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    backup_path: Path = Path(DEFAULT_CONFIG_BACKUP_PATH),
) -> None:
    """Write the Alloy config and persist a backup copy."""
    _write_file_atomic(config_path, config_text)
    _write_file_atomic(backup_path, config_text)


def restore_preserved_config(
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    backup_path: Path = Path(DEFAULT_CONFIG_BACKUP_PATH),
    preserved_path: Path = Path(DEFAULT_PACKAGE_CONFIG_BACKUP_PATH),
) -> bool:
    """Restore the preserved package config and return whether files changed."""
    if not preserved_path.exists():
        raise FileNotFoundError(f"Preserved Alloy config not found at {preserved_path}")

    content = preserved_path.read_text(encoding="utf-8")
    changed = False

    if not _file_has_content(config_path, content):
        _write_file_atomic(config_path, content)
        changed = True
    if not _file_has_content(backup_path, content):
        _write_file_atomic(backup_path, content)
        changed = True

    return changed


def preserve_default_config(
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    preserved_path: Path = Path(DEFAULT_PACKAGE_CONFIG_BACKUP_PATH),
) -> None:
    """Preserve the package default Alloy config if it exists."""
    if not config_path.exists():
        return
    if _has_generated_header(config_path):
        logger.warning("Package default config already replaced by generated config.")
        return
    if preserved_path.exists():
        if _has_generated_header(preserved_path):
            shutil.copy2(config_path, preserved_path)
        return
    preserved_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(config_path, preserved_path)


def ensure_config_dir_permissions(config_dir: str) -> None:
    """Ensure Alloy can write to its config directory when running as root."""
    if os.geteuid() != 0:
        return
    _ensure_alloy_permissions(Path(config_dir))


def _ensure_alloy_permissions(target: Path) -> None:
    ids = _alloy_ids()
    if ids is None:
        return
    uid, gid = ids
    _ensure_dir(target, uid, gid)
    _chown_tree(target, uid, gid)


def _ensure_dir(path: Path, uid: int, gid: int) -> None:
    path.mkdir(parents=True, exist_ok=True)
    try:
        os.chown(path, uid, gid)
    except PermissionError:
        logger.debug("Skipping chown for %s (insufficient permissions)", path)


def _chown_tree(path: Path, uid: int, gid: int) -> None:
    try:
        os.chown(path, uid, gid)
    except PermissionError:
        logger.debug("Skipping chown for %s (insufficient permissions)", path)
        return
    for root, dirs, files in os.walk(path):
        for name in dirs:
            try:
                os.chown(os.path.join(root, name), uid, gid)
            except PermissionError:
                logger.debug("Skipping chown for %s", os.path.join(root, name))
        for name in files:
            try:
                os.chown(os.path.join(root, name), uid, gid)
            except PermissionError:
                logger.debug("Skipping chown for %s", os.path.join(root, name))


def _alloy_ids() -> tuple[int, int] | None:
    try:
        entry = pwd.getpwnam("alloy")
        return entry.pw_uid, entry.pw_gid
    except KeyError:
        logger.warning("User/group 'alloy' not found; skipping ownership update.")
        return None


def _has_generated_header(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8") as handle:
            first_line = handle.readline().strip()
        return first_line.startswith(_GENERATED_HEADER_PREFIX)
    except OSError:
        return False


def _write_file_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(f"{path.suffix}.tmp")
    tmp_path.write_text(content, encoding="utf-8")
    tmp_path.replace(path)


def _file_has_content(path: Path, expected: str) -> bool:
    try:
        return path.read_text(encoding="utf-8") == expected
    except OSError:
        return False


def _format_custom_args(custom_args: str) -> str:
    return f'CUSTOM_ARGS="{custom_args}"'


def _strip_quotes(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value
